title: "❓[TechQA]: "
labels:
  - question
  - help wanted
body:
  - type: textarea
    id: current_issue
    attributes:
      label: 🐛 今、起きていること / Current Issue
      description: 現在直面している問題を簡潔に記載してください。 / Briefly describe the issue you are facing.
      placeholder: |
        例:  
        - ユーザー新規登録をしようと、登録ボタンを押したらエラーになった。  
        / e.g., When I click the "Register" button for user sign-up, I encounter an error.
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: 🎯 解決したいこと / Goal
      description: 実現したいことや期待する結果を記載してください。 / Describe what you want to achieve or the expected outcome.
      placeholder: |
        例:  
        - ユーザー新規登録を実装し、データベースに保存したい。  
        / e.g., I want to implement user sign-up and save data to the database.
    validations:
      required: true

  - type: textarea
    id: steps_and_results
    attributes:
      label: 🔄 試したこととその結果 / Steps Taken and Results
      description: 試した内容と、その結果を記載してください。 / Describe the steps you have taken and the results.
      placeholder: |
        例:  
        - 登録ボタンを押すと、サーバーから500エラーが返ってきた。  
        - デバッグしたところ、データベースへの接続がタイムアウトしていることが分かった。  
        / e.g., When I click the "Register" button, I receive a 500 error from the server. Debugging shows a database connection timeout.
    validations:
      required: true

  - type: textarea
    id: research_and_hypotheses
    attributes:
      label: 📚 調査内容と仮説 / Research and Hypotheses
      description: 調査した内容や考えた仮説を記載してください。 / Provide the research you've done and any hypotheses you have.
      placeholder: |
        例:  
        - 公式ドキュメントを確認し、接続タイムアウトの原因が設定不足である可能性があると考えた。  
        - Stack Overflowで類似のケースを調べたが解決策は見つからなかった。  
        / e.g., Checked the official documentation and hypothesized that the timeout is caused by misconfiguration. Searched Stack Overflow but didn't find a solution.
    validations:
      required: false

  - type: textarea
    id: code_and_logs
    attributes:
      label: 💻 関連するコードやログ / Relevant Code and Logs
      description: 問題に関連するコードやログを記載してください。 / Include relevant code snippets or logs related to the issue.
      placeholder: |
        例:  
        - エラーメッセージ: `Error: Connection timeout at db.connect`  
        - コード例: `db.connect({ host: 'localhost', port: 5432 })`  
        / e.g.,  
        - Error message: `Error: Connection timeout at db.connect`  
        - Code snippet: `db.connect({ host: 'localhost', port: 5432 })`
    validations:
      required: false

  - type: textarea
    id: additional_information
    attributes:
      label: 🗒️ 補足情報 / Additional Information
      description: 質問に関連するその他の情報を記載してください（任意）。 / Provide any additional context or considerations related to your question (optional).
      placeholder: |
        例:  
        - この問題は特定のブラウザでのみ発生する。  
        - モバイル環境では正常に動作するが、デスクトップ環境で問題が発生する。  
        / e.g., The issue occurs only on specific browsers. It works fine on mobile but fails on desktop.
    validations:
      required: false
