name: バグ報告 / Bug Report
description: バグ報告を提出してください / File a bug report
labels:
  - bug
projects:
  - y-daiki-nakamura/2
title: "[BUG]: About bug title"

body:
  - type: checkboxes
    id: checks
    attributes:
      label: "✅ 必要な情報を選択しましたか？ / Have you selected the following information?"
      description: |
        - **ラベル** / Labels  
        - **プロジェクト** / Projects  
        - **マイルストーン** / Milestone
      options:
        - label: "🏷️ ラベルを選択しました / Labels: Selected"
          required: true
        - label: "📁 プロジェクトを選択しました / Projects: Selected"
          required: true
        - label: "📅 マイルストーンを選択しました / Milestone: Selected"
          required: true

  - type: textarea
    id: description
    attributes:
      label: "🐛 バグの詳細 / Describe the bug"
      placeholder: "詳細を教えてください / Please tell us more details."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "🔁 再現手順 / To Reproduce"
      description: |
        バグを再現する手順を記載してください / Steps to reproduce the behavior:
      placeholder: |
        1. 「...」をクリックする / Go to '...'  
        2. 「....」を選択する / Click on '...'  
        3. 「....」までスクロールする / Scroll down to '...'  
        4. エラーが表示される / See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "🎯 期待する動作 / Expected behavior"
      description: |
        発生するはずの正しい動作を記載してください / A clear and concise description of what you expected to happen.
      placeholder: "正しい動作を簡潔に記載してください / A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "🖥️ 環境情報 / Environment"
      options:
        - 開発環境 / Development
        - UAT / User Acceptance Test
        - 内部検証 / Internal Verification
        - 外部検証 / External Verification
        - QA
        - その他 / Others
      default: 0
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: "🔢 バージョン / Version"
      options:
        - 1.0.1
        - 1.0.2
        - 2.0.1
      default: 0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "🗒️ 追加情報 / Additional context"
      description: |
        問題に関連する他の情報があれば記載してください / Add any other context about the problem here.
