name: Update Project Version Field
on:
  issues:
    types: [opened]

jobs:
  update-project-version:
    runs-on: ubuntu-latest
    steps:
      - name: Extract "Version" from issue body
        id: extract_version
        run: |
          BODY="${{ github.event.issue.body }}"
          # "### Version" の次の行を取得する例
          VERSION=$(echo "$BODY" | awk '/^### Version/{getline;print}')
          # VERSIONが空の場合の対処など必要なら追記
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get Project Item ID and Project ID
        id: get_ids
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_ID="${{ github.event.issue.node_id }}"
          # Issue に紐付く Project Item および Project ID を取得する
          QUERY='
          query($issueId:ID!) {
            node(id:$issueId) {
              ... on Issue {
                projectItems(first:10) {
                  nodes {
                    id
                    project {
                      id
                      title
                    }
                  }
                }
              }
            }
          }'

          # GraphQL 実行
          RESULT=$(gh api graphql -f query="$QUERY" -f issueId="$ISSUE_ID")
          ITEM_ID=$(echo "$RESULT" | jq -r '.data.node.projectItems.nodes[0].id')
          PROJECT_ID=$(echo "$RESULT" | jq -r '.data.node.projectItems.nodes[0].project.id')

          # 取得結果を出力
          echo "item_id=$ITEM_ID" >> $GITHUB_OUTPUT
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT

      - name: Get Field ID for "Version"
        id: get_field_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID="${{ steps.get_ids.outputs.project_id }}"

          # プロジェクトに紐付く全てのフィールドを取得して、"Version" という名前のフィールドIDを取得する例
          QUERY='
          query($projectId:ID!) {
            node(id:$projectId) {
              ... on ProjectNext {
                fields(first:50) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }
          }'
          RESULT=$(gh api graphql -f query="$QUERY" -f projectId="$PROJECT_ID")
          VERSION_FIELD_ID=$(echo "$RESULT" | jq -r '.data.node.fields.nodes[] | select(.name=="Version") | .id')

          if [ -z "$VERSION_FIELD_ID" ]; then
            echo "Versionフィールドが見つかりませんでした。"
            exit 1
          fi

          echo "version_field_id=$VERSION_FIELD_ID" >> $GITHUB_OUTPUT

      - name: Update the Version field in the Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID="${{ steps.get_ids.outputs.project_id }}"
          ITEM_ID="${{ steps.get_ids.outputs.item_id }}"
          FIELD_ID="${{ steps.get_field_id.outputs.version_field_id }}"
          VERSION="${{ steps.extract_version.outputs.version }}"

          # Project の Version フィールド更新
          MUTATION='
          mutation($projectId:ID!,$itemId:ID!,$fieldId:ID!,$value:String!){
            updateProjectNextItemField(input: {
              projectId:$projectId
              itemId:$itemId
              fieldId:$fieldId
              value:$value
            }) {
              projectNextItem {
                id
              }
            }
          }'

          gh api graphql -f query="$MUTATION" -f projectId="$PROJECT_ID" -f itemId="$ITEM_ID" -f fieldId="$FIELD_ID" -f value="$VERSION"
