name: Update Project Version Field
on:
  issues:
    types: [opened]

jobs:
  update-project-version:
    runs-on: ubuntu-latest
    steps:
      - name: Extract "Version" from issue body
        id: extract_version
        run: |
          BODY="${{ github.event.issue.body }}"
          # "### Version" の次の行を取得
          VERSION=$(echo "$BODY" | awk '/^### Version/{getline;print}')
          # 必要に応じてバリデーション可
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get Project and Item IDs from Issue
        id: get_ids
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO=$(echo "${{ github.event.repository.name }}")
          NUMBER=${{ github.event.issue.number }}

          QUERY='
          query($owner:String!, $repo:String!, $number:Int!) {
            repository(owner:$owner, name:$repo) {
              issue(number:$number) {
                projectItems(first: 1) {
                  edges {
                    node {
                      id
                      project {
                        id
                        title
                        url
                      }
                    }
                  }
                }
              }
            }
          }'

          RESULT=$(gh api graphql -f query="$QUERY" -F owner="$OWNER" -F repo="$REPO" -F number="$NUMBER")

          ITEM_ID=$(echo "$RESULT" | jq -r '.data.repository.issue.projectItems.edges[0].node.id')
          PROJECT_ID=$(echo "$RESULT" | jq -r '.data.repository.issue.projectItems.edges[0].node.project.id')

          if [ "$ITEM_ID" = "null" ] || [ "$PROJECT_ID" = "null" ]; then
            echo "Project or Item not found. Make sure the issue is linked to a Project V2."
            exit 1
          fi

          echo "item_id=$ITEM_ID" >> $GITHUB_OUTPUT
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT

      - name: Get Fields from Project
        id: get_fields
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID=${{ steps.get_ids.outputs.project_id }}

          QUERY='
          query($projectId:ID!) {
            node(id:$projectId) {
              ... on ProjectV2 {
                fields(first: 50) {
                  nodes {
                    ... on ProjectV2SingleSelectField {
                      __typename
                      id
                      name
                      options {
                        id
                        name
                      }
                    }
                    ... on ProjectV2Field {
                      __typename
                      id
                      name
                    }
                  }
                }
              }
            }
          }
          '

          RESULT=$(gh api graphql -f query="$QUERY" -F projectId="$PROJECT_ID")

          # Versionフィールドを検索
          VERSION_FIELD=$(echo "$RESULT" | jq -c '.data.node.fields.nodes[] | select(.name=="Version")')
          if [ -z "$VERSION_FIELD" ]; then
            echo "Version field not found."
            exit 1
          fi

          VERSION_FIELD_ID=$(echo "$VERSION_FIELD" | jq -r '.id')
          echo "version_field_id=$VERSION_FIELD_ID" >> $GITHUB_OUTPUT

          # フィールドがシングルセレクトの場合を想定 (.__typename が ProjectV2SingleSelectField)
          FIELD_TYPE=$(echo "$VERSION_FIELD" | jq -r '.__typename')
          echo "field_type=$FIELD_TYPE" >> $GITHUB_OUTPUT

          if [ "$FIELD_TYPE" = "ProjectV2SingleSelectField" ]; then
            echo "$VERSION_FIELD" | jq -c '.options' > options.json
          fi

      - name: Determine Single Select Option
        id: get_option
        if: steps.get_fields.outputs.field_type == 'ProjectV2SingleSelectField'
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"

          # options.json から該当オプションIDを探す
          OPTION_ID=$(jq -r --arg ver "$VERSION" '.[] | select(.name==$ver) | .id' options.json)

          if [ -z "$OPTION_ID" ]; then
            echo "No matching single-select option found for Version=$VERSION"
            exit 1
          fi

          echo "option_id=$OPTION_ID" >> $GITHUB_OUTPUT

      - name: Update the Version field in the Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID=${{ steps.get_ids.outputs.project_id }}
          ITEM_ID=${{ steps.get_ids.outputs.item_id }}
          VERSION="${{ steps.extract_version.outputs.version }}"
          VERSION_FIELD_ID=${{ steps.get_fields.outputs.version_field_id }}
          FIELD_TYPE=${{ steps.get_fields.outputs.field_type }}

          # フィールドタイプに応じてMutationを組み立てる
          # シングルセレクトの場合
          if [ "$FIELD_TYPE" = "ProjectV2SingleSelectField" ]; then
            OPTION_ID=${{ steps.get_option.outputs.option_id }}
            VALUE_JSON="{\"singleSelectOptionId\": \"$OPTION_ID\"}"
          else
            # テキストフィールド等の場合はこちら
            VALUE_JSON="{\"text\": \"$VERSION\"}"
          fi

          MUTATION='
          mutation($projectId:ID!,$itemId:ID!,$fieldId:ID!,$value:ProjectV2FieldValue!) {
            updateProjectV2ItemFieldValue(
              input: {
                projectId:$projectId
                itemId:$itemId
                fieldId:$fieldId
                value:$value
              }
            ) {
              projectV2Item {
                id
              }
            }
          }
          '

          # gh api graphql では、valueのオブジェクト引数を直接指定できないため、一度ファイル経由が必要か、
          # またはgithub-scriptを用いて実行することを検討してください。
          #
          # ここでは簡略化のため、github-scriptを使う例を示します。
          # (GitHub Actionsワークフロー内でgithub-scriptアクションを使用)

      - name: Update Field via github-script
        if: steps.get_fields.outputs.field_type == 'ProjectV2SingleSelectField'
        uses: actions/github-script@v6
        with:
          script: |
            const { projectId, itemId, fieldId, optionId } = process.env;
            const mutation = `mutation($projectId:ID!,$itemId:ID!,$fieldId:ID!,$value:ProjectV2FieldValue!) {
              updateProjectV2ItemFieldValue(
                input: { projectId:$projectId, itemId:$itemId, fieldId:$fieldId, value:{singleSelectOptionId:$value}}
              ) {
                projectV2Item {
                  id
                }
              }
            }`;

            await github.graphql(mutation, {
              projectId,
              itemId,
              fieldId,
              value: optionId
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ steps.get_ids.outputs.project_id }}
          itemId: ${{ steps.get_ids.outputs.item_id }}
          fieldId: ${{ steps.get_fields.outputs.version_field_id }}
          optionId: ${{ steps.get_option.outputs.option_id }}

      - name: Update Field via github-script (text fallback)
        if: steps.get_fields.outputs.field_type != 'ProjectV2SingleSelectField'
        uses: actions/github-script@v6
        with:
          script: |
            const { projectId, itemId, fieldId, version } = process.env;
            const mutation = `mutation($projectId:ID!,$itemId:ID!,$fieldId:ID!,$value:ProjectV2FieldValue!) {
              updateProjectV2ItemFieldValue(
                input: { projectId:$projectId, itemId:$itemId, fieldId:$fieldId, value:{text:$value}}
              ) {
                projectV2Item {
                  id
                }
              }
            }`;

            await github.graphql(mutation, {
              projectId,
              itemId,
              fieldId,
              value: version
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ steps.get_ids.outputs.project_id }}
          itemId: ${{ steps.get_ids.outputs.item_id }}
          fieldId: ${{ steps.get_fields.outputs.version_field_id }}
          version: ${{ steps.extract_version.outputs.version }}
